### ISSUE TITLE
Action fails with self hosted registry

### ISSUE THREAD

**Issue by coolio85** [serversideup/github-action-docker-swarm-deploy#3]
It appears the current implementation of this action is only compatible with Docker Hub or the Github container registry. This poses issues when trying to use ECR or Digital Ocean (or even a self hosted one). I'm interested to know what direction you would take with this?

From my understanding there isn't a way to keep the functionality of logging in with multiple registries if you wanted to use a registry that isn't docker or github

**Comment by jaydrogers** [comment]
Let me see if I can clean this up. Would love to support other & multiple registries 👍

**Comment by jaydrogers** [comment]
I just added a commit to support self-hosted registries 👍

I don't know why I structured it the way I did it before. This is on `@main` but it will be made available with `v2` once I have things stabilized

**Comment by jaydrogers** [comment]
This is now available in v2 🥳

https://github.com/serversideup/github-action-docker-swarm-deploy/releases/tag/v2
